// MARK: - Action IDs

#define ACTION_ID_SET_MIDI_IN_DEVICE	0
#define ACTION_ID_SET_MIDI_OUT_DEVICE	1
#define ACTION_ID_OPEN_MIDI_IN_DEVICE	2
#define ACTION_ID_CLOSE_MIDI_IN_DEVICE	3
#define ACTION_ID_ENUM_MIDI_IN_DEVICES	4
#define ACTION_ID_OPEN_MIDI_OUT_DEVICE	5
#define ACTION_ID_CLOSE_MIDI_OUT_DEVICE	6
#define ACTION_ID_ENUM_MIDI_OUT_DEVICES	7
#define ACTION_ID_PLAY_LAST_NOTE		8
#define ACTION_ID_SEND_MSG_TO_OUT_DEV	9

// MARK: - Condition IDs
#define CONDITION_ID_ON_INPUT			0
#define CONDITION_ID_ON_IN_DEVICE_ENUM	1
#define CONDITION_ID_ON_OUT_DEVICE_ENUM	2
#define CONDITION_ID_ON_ERROR			3

// MARK: - Expression IDs
#define EXPRESSION_ID_GET_NUM_IN_DEVICES		0
#define EXPRESSION_ID_GET_NUM_OUT_DEVICES		1
#define EXPRESSION_ID_GET_NAME_IN_DEVICE		2
#define EXPRESSION_ID_GET_NAME_OUT_DEVICE		3
#define EXPRESSION_ID_GET_NOTE_ACTUAL_NOTE		4
#define EXPRESSION_ID_GET_NOTE_NUM_IN_OCTAVE	5
#define EXPRESSION_ID_GET_NOTE_NAME				6
#define EXPRESSION_ID_GET_NOTE_OCTAVE_NUM		7
#define EXPRESSION_ID_GET_NOTE_RAW_DATA_ONE		8
#define EXPRESSION_ID_GET_NOTE_RAW_DATA_TWO		9
#define EXPRESSION_ID_GET_NOTE_RAW_STATUS		10
#define EXPRESSION_ID_ENUM_IN_NAME				11
#define EXPRESSION_ID_ENUM_IN_INDEX				12
#define EXPRESSION_ID_ENUM_OUT_NAME				13
#define EXPRESSION_ID_ENUM_OUT_INDEX			14
#define EXPRESSION_ID_ON_ERROR_GET_TYPE			15
#define EXPRESSION_ID_ON_ERROR_GET_DESC			16

// MARK: - MISC IDs
#define DISABLED_ID	999

